/* eslint-disable prettier/prettier */
import type { Metadata } from "next";

import Head from "next/head";


import "./globals.css";
import Footer from "./components/Footer/Footer";
import Title from "./components/Title/Title";
import SwitchMenu from "./components/SwitchMenu/SwitchMenu"
import BgFood from "./components/BgFood/BgFood"
import Navbar from "./components/Navbar/Navbar"
import PayMethod from "./components/PayMethod/PayMethod"
import Congelados from "./components/Congelados/Congelados"

export const metadata: Metadata = {
  title: "comidasliliana2024",
  description: "Generated by appncy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <Head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600&display=swap" rel="stylesheet" />
        </Head>
      <body className="bg-[#444749] pb-12">
        <BgFood />
        <Title />
        <SwitchMenu />
        <main className="">{children}</main>
        <PayMethod />
        <Congelados />
        <Navbar />
        
      </body>
    </html>
  );
}
