/* eslint-disable prettier/prettier */
import type { Metadata } from "next";



import "./globals.css";
import Footer from "./components/Footer/Footer";
import Title from "./components/Title/Title";

export const metadata: Metadata = {
  title: "comidasliliana2024",
  description: "Generated by appncy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased">
        <Title />

        <main className="py-8">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
